### ISSUE TITLE
Missing .env.example

### ISSUE THREAD

**Issue by Volxz** [salamander2/TimeAndPlace#4]
The repository should have a .env.example (a .env with a different name and default values) you can probably just copy your current one to .env.example and remove any private fields.

**Comment by salamander2** [comment]
Hiya!

I deleted it. Why do I need a .env.example when I have a .env?

**Comment by Volxz** [comment]
.env is ignored when you push to GitHub as it contains private information such as your database password. The .env.example contains all the default settings for the application so when you install it you copy the .env.example to .env and then modify .env with your database info etc

**Comment by salamander2** [comment]
Done. It's in the dev branch right now, but it will end up in master as well, as soon as I merge the two branches.
